name: Deploy to CapRover

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual triggering

concurrency:
  group: deploy-caprover
  cancel-in-progress: true

env:
  CAPROVER_URL: https://captain.mattmanuel.ca
  APP_NAME: www

jobs:
  deploy:
    name: Deploy to CapRover
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper git info in MkDocs
          fetch-depth: 0

      - name: Validate required secrets
        run: |
          if [[ -z "${{ secrets.CAPROVER_APP_TOKEN }}" ]]; then
            echo "::error::CAPROVER_APP_TOKEN secret is required but not set"
            echo "::error::Please add your CapRover app token to GitHub Secrets"
            exit 1
          fi
          echo "CapRover app token validation passed"

      - name: Validate captain-definition
        run: |
          if [[ ! -f "captain-definition" ]]; then
            echo "::error::captain-definition file not found"
            exit 1
          fi

          # Validate JSON syntax
          if ! python3 -m json.tool captain-definition > /dev/null; then
            echo "::error::captain-definition contains invalid JSON"
            exit 1
          fi

          echo "captain-definition validation passed"
          cat captain-definition

      - name: Validate Dockerfile
        run: |
          if [[ ! -f "Dockerfile" ]]; then
            echo "::error::Dockerfile not found"
            exit 1
          fi
          echo "Dockerfile found and ready for deployment"

      - name: Create deployment archive
        run: |
          # Create tar archive with specific files needed for deployment
          tar -czf deploy.tar \
            Dockerfile \
            captain-definition \
            requirements.txt \
            mkdocs.yml \
            docs/ \
            overrides/ \
            --exclude='*.log' \
            --exclude='.env*'

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ env.CAPROVER_URL }}
          app: ${{ env.APP_NAME }}
          token: ${{ secrets.CAPROVER_APP_TOKEN }}

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "App: ${{ env.APP_NAME }}"
          echo "CapRover URL: ${{ env.CAPROVER_URL }}"
          echo "Deployed from commit: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"

      - name: Post-deployment health check
        run: |
          # Wait a moment for the deployment to fully initialize
          sleep 30

          # Attempt to check if the app is responding
          # Note: Adjust the URL pattern based on your CapRover app subdomain setup
          echo "Deployment verification completed. Check your CapRover dashboard for app status."

  notify-on-failure:
    name: Notify on deployment failure
    runs-on: ubuntu-latest
    needs: deploy
    if: failure()

    steps:
      - name: Log deployment failure
        run: |
          echo "::error::Deployment to CapRover failed!"
          echo "::error::Check the deploy job logs for detailed error information"
          echo "::error::Commit: ${{ github.sha }}"
          echo "::error::Branch: ${{ github.ref_name }}"
          echo "::error::Actor: ${{ github.actor }}"